config/routes.rb
Rails.application.routes.draw do
  resources :shops, only: [:index, :show] do
    get :vending, on: :collection
    get :buying, on: :collection
  end
  resources :items, only: [:index, :show] do
    get :opportunities, on: :collection
  end

  root 'home#index'
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_items
  has_many :items, through: :shop_items

  scope :open, -> { where(state: 'Open') }
  scope :updating, -> { where(state: 'Updating') }
  scope :closed, -> { where(state: 'Closed') }

  scope :vending, -> { where(shop_type: 'V') }
  scope :buying, -> { where(shop_type: 'B') }

  def open?
    state == 'Open'
  end
  def closed?
    state == 'Closed'
  end

  def nice_shop_type
    shop_type == 'V' ? 'Vendor' : 'Buyer'
  end

  def self.sync!
    # Mark all open shops as currently updating
    Shop.open.update_all "state='Updating'"

    # Get all shops currently out there.
    OriginApi.shops.each do |server_market|
      Shop.find_or_initialize_by(username: server_market['owner'], start_date: server_market['creation_date']).tap do |shop|
        shop.transaction do
          shop.title = server_market['title']
          shop.location_map = server_market['location']['map']
          shop.location_x = server_market['location']['x']
          shop.location_y = server_market['location']['y']
          shop.shop_type = server_market['type']
          shop.save!

          shop.shop_items.active.update_all "state='Updating'"

          # Go through the items currently in the shop and update them
          server_market['items'].each do |server_item|
            begin
              shop.shop_items.updating.find_or_initialize_by(item_id: Item.find_by(uid: server_item['item_id']).id,
                                                             price: server_item['price'],
                                                             refine: server_item['refine'],
                                                             cards: server_item['cards'],
                                                             element: server_item['element'],
                                                             star_crumbs: server_item['star_crumbs'],
                                                             forger: server_item['creator'],
                                                             beloved: server_item['beloved']
                                                           ).tap do |shop_item|
                # Save the original number of this item that were there to be sold
                if shop_item.new_record?
                  shop_item.original_quantity = server_item['amount']
                end

                shop_item.quantity = server_item['amount']
                shop_item.transacted_quantity = shop_item.original_quantity - server_item['amount']

                shop_item.state = 'Active'
                shop_item.save!
              rescue Exception => e
                byebug
              end
            end
          end

          # Any shop items that aren't active were sold. Mark them as sold
          shop.shop_items.updating.each do |shop_item|
            shop_item.update_attributes({
              transacted_quantity: shop_item.original_quantity,
              quantity: 0,
              state: 'Sold',
              sold_at: Time.now
            })
          end

          shop.state = 'Open'
          shop.save!
        end
      end
    end

    # Mark all shop items that we don't know about as neither sold or unsold
    Shop.updating.each do |shop|
      shop.shop_items.active.update_all "state='Unsold'"
    end
    Shop.updating.update_all ["closed_date=?", Time.now]
    Shop.updating.update_all "state='Closed'"
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show]

  include Pagy::Backend

  # GET /shops
  def index
    @pagy, @shops = pagy(Shop.open.order(start_date: :desc), items: 200)
  end

  def vending
    @pagy, @shops = pagy(Shop.open.vending.order(start_date: :desc), items: 200)
    render :index
  end

  def buying
    @pagy, @shops = pagy(Shop.open.buying.order(start_date: :desc), items: 200)
    render :index
  end

  # GET /shops/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def shop_params
      params.require(:shop).permit(:title, :username, :location_map, :location_x, :location_y, :start_date, :shop_type, :open)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.haml
.container.flex
  .card{ class: 'w-3/4' }
    %h1 Listing shops

    %table
      %thead
        %tr
          %th Shop type
          %th Title
          %th Location
          %th Open Date
          %th When?

      %tbody
        - @shops.each do |shop|
          %tr
            %td= shop.nice_shop_type
            %td
              = link_to shop.title, shop
              by
              = shop.username
            %td= "#{shop.location_map} (#{shop.location_x}, #{shop.location_y})"
            %td
              = shop.start_date.strftime("%Y.%d.%m @ %H:%M:%S")
            %td= time_ago_in_words shop.start_date

    %br

    = pagy_nav(@pagy).html_safe

  .ml-8{ class: 'w-1/4' }
    .card
      Something

app/views/shops/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @shop.title
%p
  %b Username:
  = @shop.username
%p
  %b Location map:
  = @shop.location_map
%p
  %b Location x:
  = @shop.location_x
%p
  %b Location y:
  = @shop.location_y
%p
  %b Start date:
  = @shop.start_date
%p
  %b Shop type:
  = @shop.shop_type
%p
  %b State:
  = @shop.state

%table
  %thead
    %tr
      %td
      %td Item
      %td Price

      %td Quantity
      %td Original Quantity
      %td Transacted Quantity
      %td Cards
  %tbody
    - @shop.shop_items.includes(:item).order(price: :desc).each do |shop_item|
      %tr
        %td
          %img{ src: shop_item.item.icon }
        %td= link_to shop_item.full_name, item_path(shop_item.item)
        %td= number_with_delimiter shop_item.price
        %td= number_with_delimiter shop_item.quantity
        %td= shop_item.original_quantity
        %td= shop_item.transacted_quantity
        %td
          - if shop_item.cards && shop_item.cards.length > 0
            %ul
            - Item.where(uid: shop_item.cards).each do |card|
              %li= link_to card.name, item_path(card)


= link_to 'Back', shops_path