config/routes.rb
Rails.application.routes.draw do
  resources :shops, only: [:index, :show] do
    get :vending, on: :collection
    get :buying, on: :collection
  end
  resources :items, only: [:index, :show] do
    get :opportunities, on: :collection
  end

  root 'home#index'
end

app/models/item.rb
class Item < ApplicationRecord
  ITEM_TYPES = {
    'IT_HEALING': 'Healing items',
    'IT_UNKNOWN': 'Unknown item type',
    'IT_USABLE': 'Other usable items',
    'IT_ETC': 'Misc items',
    'IT_WEAPON': 'Weapons',
    'IT_ARMOR': 'Armors',
    'IT_CARD': 'Cards',
    'IT_PETEGG': 'Pet eggs',
    'IT_PETARMOR': 'Pet accessories',
    'IT_UNKNOWN2': 'Unknown items (unused)',
    'IT_AMMO': 'Ammunitions',
    'IT_DELAYCONSUME': 'Consumable items (triggering additional actions)',
    'IT_CASH': 'Cash shop items'
  }.freeze
  ITEM_SUBTYPES = {
    'W_FIST': 'Unknown weapon (unused)',
    'W_DAGGER': 'Daggers',
    'W_1HSWORD': '1-hand swords',
    'W_2HSWORD': '2-hand swords',
    'W_1HSPEAR': '1-hand spears',
    'W_2HSPEAR': '2-hand spears',
    'W_1HAXE': '1-hand axes',
    'W_2HAXE': '2-hand axes',
    'W_MACE': '1-hand maces',
    'W_2HMACE': '2-hand maces',
    'W_STAFF': 'Staves',
    'W_BOW': 'Bows',
    'W_KNUCKLE': 'Knuckles',
    'W_MUSICAL': 'Musical instruments',
    'W_WHIP': 'WhipsW_BOOK: Books',
    'W_KATAR': 'Katars',
    'W_REVOLVER': 'Pistols',
    'W_RIFLE': 'Rifles',
    'W_GATLING': 'Gatling guns',
    'W_SHOTGUN': 'Shotguns',
    'W_GRENADE': 'Grenades',
    'W_HUUMA': 'Huuma shuriken',
    'A_ARROW': 'Arrows',
    'A_DAGGER': 'Throwing daggers',
    'A_BULLET': 'BulletsA_SHELL: Shells',
    'A_GRENADE': 'Grenades',
    'A_SHURIKEN': 'Shuriken',
    'A_KUNAI': 'Kunai',
    'A_CANNONBALL': 'Cannon balls',
    'A_THROWWEAPON': 'Other throwing weapons'
  }.freeze
  validates :uid, uniqueness: true
  validates :unique_name, uniqueness: true

  has_many :shop_items
  has_many :shops, through: :shop_items

  scope :opportunities, -> { where('best_selling_price < best_buying_price') }

  def card?
    item_type == 'IT_CARD'
  end

  def nice_item_type
    ITEM_TYPES[item_type.to_sym] if item_type
  end
  def nice_item_subtype
    ITEM_SUBTYPES[item_subtype.to_sym] if item_subtype
  end

  def name_with_slots
    slots.nil? ? name : "#{name}[#{slots}]"
  end

  def market_opportunity
    return 0 if best_buying_price < best_selling_price

    if best_buyer = shop_items.buying.where("price < #{best_selling_price}").first
      [selling_below_market_value.sum(:quantity), buying_above_market_value.sum(:quantity)].min * best_buyer.price
    else
      0
    end
  end

  def selling_below_market_value
    shop_items.vending.active.where(["price < ?", best_buying_price])
  end

  def buying_above_market_value
    shop_items.buying.active.where(["price > ?", best_selling_price])
  end

  def avg_best_selling_price hours
    all_hours = (0..hours).to_a.collect do |hour|
      best_selling_price_at(hour.hours.ago, [hours.hours.ago, Time.now])
    end.compact

    avg(all_hours)
  end

  def mean_best_selling_price hours
    all_hours = (0..hours).to_a.collect do |hour|
      best_selling_price_at(hour.hours.ago, [hours.hours.ago, Time.now])
    end.compact

    mean(all_hours)
  end

  def avg arr
    arr.length == 0 ? 0 : arr.inject(0) { |result, el| result + el } / arr.length
  end

  def mean arr
    if arr.length == 0
      0
    elsif arr.length % 2 == 0
      n = arr.length/2
      (arr[n] + arr[n+1]) / 2
    else
      arr[arr.length/2]
    end
  end

  def best_prices start_time, end_time
    @best_prices = @best_prices || {}
    key = [start_time, end_time].join(',')
    @best_prices[key] = @best_prices[key] || ShopItem.where(item_id: id)
      .joins(:shop)
      .where(["start_date < ? AND (closed_date IS NULL OR closed_date > ?)", end_time, start_time])
      .where(refine: nil)
      .where(cards: nil)
      .includes(:shop)
      .collect { |shop_item| {
        closed_date: shop_item.shop.closed_date,
        start_date: shop_item.shop.start_date,
        price: shop_item.price
      } }
  end

  # Get the percentage of hours this item was available
  def availability start_time, end_time
    hours = ((end_time - start_time) / 3600).round - 1
    available = (0..hours).to_a.collect do |hour|
      best_selling_price_at(start_time + hour.hours, [start_time, end_time])
    end.compact

    available.length*1.0 / (hours+1)*1.0 * 100
  end

  def best_selling_price_in start_time, end_time
    best_prices(start_time, end_time).collect { |shop_item| shop_item[:price] }.sort.first || "-"
  end

  def best_selling_price_at time, time_range
    best_prices(time_range.first, time_range.last).filter do |shop_item|
      shop_item[:start_date] <= time && (shop_item[:closed_date].nil? || shop_item[:closed_date] >= time)
    end.collect { |shop_item| shop_item[:price] }.sort.first
  end

  def self.sync!
    # Items
    OriginApi.items.each do |server_item|
      Item.find_or_initialize_by(uid: server_item['item_id']).tap do |item|
        item.unique_name = server_item['unique_name']
        item.name = server_item['name']
        item.item_type = server_item['type']
        item.item_subtype = server_item['subtype']
        item.npc_price = server_item['npc_price']
        item.slots = server_item['slots']
        item.save
      end
    end

    # Items
    OriginApi.icons.each do |server_icon|
      Item.find_or_initialize_by(uid: server_icon['item_id']).tap do |item|
        item.icon = server_icon['icon']
        item.save
      end
    end
  end

  def self.best_prices!
    Item.all.each do |item|
      item.best_selling_price = ShopItem.vending.where(item_id: item.id).order(:price).first.try(:price)
      item.best_buying_price = ShopItem.buying.where(item_id: item.id).order(price: :desc).first.try(:price)
      item.save
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  include Pagy::Backend

  # GET /items
  def index
    if params[:q]
      @pagy, @items = pagy(Item.ransack(name_cont: params[:q]).result(distinct: true), items: 250)
    else
      @pagy, @items = pagy(Item.order(:name), items: 250)
    end
  end

  # GET /items/1
  def show
  end

  def opportunities
    @items = Item.opportunities
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:uid, :unique_name, :name, :type, :subtype, :npc_price, :slots, :icon)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
%h1 Listing items

= form_with(url: items_path, method: "get") do
  = label_tag(:q, "Search for:")
  = text_field_tag(:q)
  = submit_tag("Search")

%table
  %thead
    %tr
      %th Icon
      %th Name
      %th Type
      %th Subtype
      %th Npc price

  %tbody
    - @items.each do |item|
      %tr
        %td
          %img{ src: item.icon }
        %td= link_to item.name_with_slots, item
        %td= item.nice_item_type
        %td= item.nice_item_subtype
        %td= item.npc_price

%br

= pagy_nav(@pagy).html_safe

app/views/items/opportunities.html.haml
%h1 Market Opportunities

%table
  %thead
    %tr
      %th Icon
      %th Name
      %th Best Sale Price
      %th Best Buy Price
      -# %th Opportunity
      %th Good/Bad Ratio

  %tbody
    - @items.each do |item|
      %tr
        %td
          %img{ src: item.icon }
        %td= link_to item.name, item
        %td= number_with_delimiter item.best_selling_price
        %td= number_with_delimiter item.best_buying_price
        -# %td= number_with_delimiter item.market_opportunity
        %td
          = item.selling_below_market_value.sum(:quantity)
          = "/"
          = item.buying_above_market_value.sum(:quantity)

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name_with_slots

%p
  %b Uid:
  = @item.uid
%p
  %b Type:
  = @item.nice_item_type
%p
  %b Subtype:
  = @item.nice_item_subtype
%p
  %b Npc price:
  = number_with_delimiter @item.npc_price
%p
  %b Slots:
  = @item.slots
%p
  %b Icon:
  %img{ src: @item.icon }

%p
  %b 7-Day Avg Avg Selling Price
  = number_with_delimiter @item.avg_best_selling_price(24*7)
%p
  %b 7-Day Avg Mean Selling Price
  = number_with_delimiter @item.mean_best_selling_price(24*7)


%h2 Price Over Time
%table
  %tr
    %th Date
    %th Best Price
    %th Availability
  - (0..10).to_a.each do |i|
    - day_start = i.days.ago.beginning_of_day
    %tr
      %td= day_start.strftime("%B %-d, %Y")
      %td= number_with_delimiter @item.best_selling_price_in(day_start, day_start.end_of_day)
      %td= number_to_percentage @item.availability(day_start, day_start.end_of_day), precision: 0


%h2 Selling
- @active_items = @item.shop_items.active.vending.order(:price)
- if @active_items.length == 0
  %p There are no active shops selling this item.
- else
  %table
    %thead
      %tr
        %th
        %th Item
        %th Shop
        %th Price
        %th Quantity
        %th Vendor
        %th Location
        %th Cards

    - @active_items.each do |shop_item|
      %tr
        %td
          %img{ src: shop_item.item.icon }
        %td= shop_item.full_name
        %td= link_to shop_item.shop.title, shop_path(shop_item.shop)
        %td= number_with_delimiter shop_item.price
        %td= number_with_delimiter shop_item.quantity
        %td= link_to shop_item.shop.username, shop_item.shop
        %td= "#{shop_item.shop.location_map} (#{shop_item.shop.location_x}, #{shop_item.shop.location_y})"
        %td
          - if shop_item.cards && shop_item.cards.length > 0
            %ul
              - Item.where(uid: shop_item.cards).each do |card|
                %li= link_to card.name, item_path(card)

- if @item.card?
  %h2 Selling (Already slotted)
  - @active_slotted_items = ShopItem.active.vending.order(:price).where("? = ANY(cards)", @item.uid)
  - if @active_slotted_items.length == 0
    %p There are no active shops selling this card already slotted at this time
  - else
    %table
      %thead
        %tr
          %th
          %th Shop Name
          %th Price
          %th Quantity
          %th Vendor
          %th Location
          %th Cards
      - @active_slotted_items.each do |shop_item|
        %tr
          %td
            %img{ src: shop_item.item.icon }
          %td= link_to shop_item.shop.title, shop_item.shop
          %td= number_with_delimiter shop_item.price
          %td= number_with_delimiter shop_item.quantity
          %td= link_to shop_item.shop.username, shop_path(shop_item.shop)
          %td= "#{shop_item.shop.location_map} (#{shop_item.shop.location_x}, #{shop_item.shop.location_y})"
          %td
            - if shop_item.cards && shop_item.cards.length > 0
              %ul
                - Item.where(uid: shop_item.cards).each do |card|
                  %li= link_to card.name, item_path(card)

%h2 Recently Sold
- @recently_sold = ShopItem.sold.includes(:item).where(item_id: @item.id).limit(50).order(sold_at: :desc)
- if @recently_sold.length == 0
  %p There are no recent sales of this item on the market.
- else
  %table
    %thead
      %tr
        %th
        %th Item
        %th Price
        %th Date Sold
        %th Cards
    - @recently_sold.each do |shop_item|
      %tr
        %td
          %img{ src: shop_item.item.icon }
        %td= link_to shop_item.full_name, shop_item.item
        %td= number_with_delimiter shop_item.price
        %td= time_ago_in_words shop_item.sold_at
        %td
          - if shop_item.cards && shop_item.cards.length > 0
            %ul
              - Item.where(uid: shop_item.cards).each do |card|
                %li= link_to card.name, item_path(card)





%h2 Buying
- @active_items = @item.shop_items.active.buying.order(price: :desc)
- if @active_items.length == 0
  %p There are no active shops buying this item.
- else
  %table
    %thead
      %tr
        %th
        %th Shop Name
        %th Price
        %th Quantity
        %th Vendor
        %th Location

    - @active_items.each do |shop_item|
      %tr
        %td
          %img{ src: shop_item.item.icon }
        %td= link_to shop_item.shop.title, shop_path(shop_item.shop)
        %td= number_with_delimiter shop_item.price
        %td= number_with_delimiter shop_item.quantity
        %td= link_to shop_item.shop.username, shop_item.shop
        %td= "#{shop_item.shop.location_map} (#{shop_item.shop.location_x}, #{shop_item.shop.location_y})"

= link_to 'Back', items_path